# ------------------------------------------------------------------------------
# i3status configuration file
# Reference : https://i3wm.org/i3status/manpage.html
#
# Custom status bar configuration for i3wm featuring system metrics 
# (CPU, RAM, Storage, Network, Battery) with Dracula color palette.
# ------------------------------------------------------------------------------

# generate a status line with i3status
general {
        output_format = "i3bar"
        colors = true
        interval = 5
}

# define the order of the status line
order += "load"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "battery 0"
order += "tztime makassar"

# define the status line components
load {
        format = "󰉨 %1min %5min %15min"
        max_threshold = "4.0"
        format_above_threshold = "󰉪 %1min %5min %15min"
}

# define the CPU usage component with thresholds and formatting
cpu_usage {
        format = " %usage"
        max_threshold = 75
        format_above_threshold = " %usage"
        degraded_threshold = 25
        format_above_degraded_threshold = " %usage"
}

# define the CPU temperature component with thresholds and formatting
cpu_temperature 0 {
        format = " %degrees °C"
        max_threshold = 80
        format_above_threshold = " %degrees °C"
        path = "/sys/devices/platform/coretemp.0/hwmon/hwmon5/temp1_input"
}

# define the memory usage component with thresholds and formatting
memory {
        format = " %used | %total (%percentage_used)"
        unit = "auto"
        decimals = 1
        threshold_degraded = "10%"
        threshold_critical = "5%"
        format_degraded = " %used | %total"
}

# define the disk usage component with thresholds and formatting
disk "/" {
        format = " %free | %total (%percentage_free)"
        low_threshold = 5
        format_below_threshold = " %free | %total (%percentage_used)"
        threshold_type = "%percentage_free"
}

# define the battery component with thresholds and formatting
battery 0 {
        format = "%status %percentage %remaining %emptytime"
        format_percentage = "%.02f%s"
        status_chr = "  Charge"
        status_bat = "  Battery"
        status_full = "  Full"
        status_idle = "  Idle"
        low_threshold = 30
        threshold_type = "time"
        path = "/sys/class/power_supply/BAT%d/uevent"
}

# define the timezone component with formatting
tztime makassar {
        format = " %H:%M |  %d/%m/%Y"
        timezone = "Asia/Makassar"
}
